<?xml version="1.0"?>
<robot name="scout_mini" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel.xacro" />

    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <xacro:property name="frame_length" value="0.35" />
    <xacro:property name="frame_width" value="0.27" />
    <xacro:property name="frame_height" value="0.14" />
    <xacro:property name="frame_profile" value="0.04" />
    <xacro:property name="frame_z_offset" value="-0.05" />

    <material name="aluminum">
        <color rgba="0.7 0.7 0.7 1" />
    </material>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 -1.5707" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 -1.5707" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base_link.dae" />
            </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="60" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <xacro:scout_mini_wheel wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel>
    <xacro:scout_mini_wheel wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel>
    <xacro:scout_mini_wheel wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel>
    <xacro:scout_mini_wheel wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel>

    <link name="front_mount" />
    <joint name="front_mount_joint" type="fixed">
        <origin xyz="0.175 0 0.068999" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="front_mount" />
    </joint>

    <link name="rear_mount" />
    <joint name="rear_mount_joint" type="fixed">
        <origin xyz="-0.175 0 0.068999" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="rear_mount" />
    </joint>

    <xacro:include filename="$(arg urdf_extras)" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini.gazebo" />
    <xacro:include filename="$(find sick_safetyscanners_description)/urdf/nanoscan3.urdf.xacro" />

    <!-- Aluminum frame (40x40) -->
    <joint name="frame_joint" type="fixed">
        <origin xyz="0 0 ${base_z_size/2 + frame_z_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="frame_link" />
    </joint>

    <link name="frame_link">
        <!-- Vertical posts -->
        <visual>
            <origin xyz="${frame_length/2 - frame_profile/2} ${frame_width/2 - frame_profile/2} ${frame_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_profile} ${frame_profile} ${frame_height}" />
            </geometry>
            <material name="aluminum" />
        </visual>
        <visual>
            <origin xyz="${frame_length/2 - frame_profile/2} ${-(frame_width/2 - frame_profile/2)} ${frame_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_profile} ${frame_profile} ${frame_height}" />
            </geometry>
            <material name="aluminum" />
        </visual>
        <visual>
            <origin xyz="${-(frame_length/2 - frame_profile/2)} ${frame_width/2 - frame_profile/2} ${frame_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_profile} ${frame_profile} ${frame_height}" />
            </geometry>
            <material name="aluminum" />
        </visual>
        <visual>
            <origin xyz="${-(frame_length/2 - frame_profile/2)} ${-(frame_width/2 - frame_profile/2)} ${frame_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_profile} ${frame_profile} ${frame_height}" />
            </geometry>
            <material name="aluminum" />
        </visual>

        <!-- Top perimeter (4 bars) -->
        <visual>
            <origin xyz="0 ${frame_width/2 - frame_profile/2} ${frame_height - frame_profile/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_length - 2*frame_profile} ${frame_profile} ${frame_profile}" />
            </geometry>
            <material name="aluminum" />
        </visual>
        <visual>
            <origin xyz="0 ${-(frame_width/2 - frame_profile/2)} ${frame_height - frame_profile/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_length - 2*frame_profile} ${frame_profile} ${frame_profile}" />
            </geometry>
            <material name="aluminum" />
        </visual>
        <visual>
            <origin xyz="${frame_length/2 - frame_profile/2} 0 ${frame_height - frame_profile/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_profile} ${frame_width - 2*frame_profile} ${frame_profile}" />
            </geometry>
            <material name="aluminum" />
        </visual>
        <visual>
            <origin xyz="${-(frame_length/2 - frame_profile/2)} 0 ${frame_height - frame_profile/2}" rpy="0 0 0" />
            <geometry>
                <box size="${frame_profile} ${frame_width - 2*frame_profile} ${frame_profile}" />
            </geometry>
            <material name="aluminum" />
        </visual>
    </link>
    
    <!-- NanoScan3 2D激光雷达 -->
    <xacro:nanoscan3 prefix="nano" parent_link="base_link" topic="/scan" robot_namespace="$(arg robot_namespace)">
        <!-- 雷达位姿在这里调整 -->
        <origin xyz="0.13 -0.045 ${base_z_size/2 + frame_height + frame_z_offset}" rpy="0 0 1.57079632679"/>
    </xacro:nanoscan3>

</robot>
